# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kmeans_dialog_base.ui'
#
# Created: Fri Jun 17 23:36:00 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_KmeansDialog(object):
    def setupUi(self, KmeansDialog):
        KmeansDialog.setObjectName(_fromUtf8("KmeansDialog"))
        KmeansDialog.resize(814, 434)
        KmeansDialog.setSizeGripEnabled(True)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(KmeansDialog)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.widgetStats = QtGui.QWidget(KmeansDialog)
        self.widgetStats.setMinimumSize(QtCore.QSize(341, 331))
        self.widgetStats.setMaximumSize(QtCore.QSize(360, 16777215))
        self.widgetStats.setObjectName(_fromUtf8("widgetStats"))
        self.gridLayout = QtGui.QGridLayout(self.widgetStats)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.widgetStats)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.lstStatistics = QtGui.QTableWidget(self.widgetStats)
        self.lstStatistics.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lstStatistics.setAutoFillBackground(False)
        self.lstStatistics.setAutoScroll(True)
        self.lstStatistics.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lstStatistics.setAlternatingRowColors(True)
        self.lstStatistics.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.lstStatistics.setTextElideMode(QtCore.Qt.ElideLeft)
        self.lstStatistics.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.lstStatistics.setShowGrid(True)
        self.lstStatistics.setGridStyle(QtCore.Qt.SolidLine)
        self.lstStatistics.setWordWrap(False)
        self.lstStatistics.setCornerButtonEnabled(False)
        self.lstStatistics.setColumnCount(3)
        self.lstStatistics.setObjectName(_fromUtf8("lstStatistics"))
        self.lstStatistics.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.lstStatistics.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.lstStatistics.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.lstStatistics.setHorizontalHeaderItem(2, item)
        self.lstStatistics.horizontalHeader().setVisible(True)
        self.lstStatistics.horizontalHeader().setCascadingSectionResizes(False)
        self.lstStatistics.horizontalHeader().setDefaultSectionSize(100)
        self.lstStatistics.horizontalHeader().setHighlightSections(True)
        self.lstStatistics.horizontalHeader().setMinimumSectionSize(20)
        self.lstStatistics.horizontalHeader().setSortIndicatorShown(False)
        self.lstStatistics.horizontalHeader().setStretchLastSection(True)
        self.lstStatistics.verticalHeader().setVisible(False)
        self.lstStatistics.verticalHeader().setHighlightSections(False)
        self.lstStatistics.verticalHeader().setSortIndicatorShown(True)
        self.lstStatistics.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.lstStatistics, 6, 0, 1, 3)
        self.label_3 = QtGui.QLabel(self.widgetStats)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 3)
        self.label = QtGui.QLabel(self.widgetStats)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 3)
        self.cmbLayers = QtGui.QComboBox(self.widgetStats)
        self.cmbLayers.setObjectName(_fromUtf8("cmbLayers"))
        self.gridLayout.addWidget(self.cmbLayers, 0, 1, 1, 2)
        self.spnNum = QtGui.QSpinBox(self.widgetStats)
        self.spnNum.setMinimum(2)
        self.spnNum.setMaximum(10)
        self.spnNum.setProperty("value", 5)
        self.spnNum.setObjectName(_fromUtf8("spnNum"))
        self.gridLayout.addWidget(self.spnNum, 2, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.widgetStats)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.progressBar = QtGui.QProgressBar(self.widgetStats)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout.addWidget(self.progressBar)
        self.buttonBox = QtGui.QDialogButtonBox(self.widgetStats)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 0, 1, 3)
        self.cmbDis = QtGui.QComboBox(self.widgetStats)
        self.cmbDis.setObjectName(_fromUtf8("cmbDis"))
        self.cmbDis.addItem(_fromUtf8(""))
        self.cmbDis.addItem(_fromUtf8(""))
        self.cmbDis.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDis, 1, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.widgetStats)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.widgetStats)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 1)
        self.openBtn = QtGui.QPushButton(self.widgetStats)
        self.openBtn.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openBtn.sizePolicy().hasHeightForWidth())
        self.openBtn.setSizePolicy(sizePolicy)
        self.openBtn.setMinimumSize(QtCore.QSize(30, 0))
        self.openBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.openBtn.setBaseSize(QtCore.QSize(0, 0))
        self.openBtn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.openBtn.setIconSize(QtCore.QSize(16, 16))
        self.openBtn.setAutoRepeatDelay(300)
        self.openBtn.setAutoDefault(True)
        self.openBtn.setDefault(False)
        self.openBtn.setFlat(False)
        self.openBtn.setObjectName(_fromUtf8("openBtn"))
        self.gridLayout.addWidget(self.openBtn, 3, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.widgetStats)
        self.widgetPlot = QtGui.QWidget(KmeansDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPlot.sizePolicy().hasHeightForWidth())
        self.widgetPlot.setSizePolicy(sizePolicy)
        self.widgetPlot.setMinimumSize(QtCore.QSize(340, 330))
        self.widgetPlot.setObjectName(_fromUtf8("widgetPlot"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widgetPlot)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layoutPlot = QtGui.QVBoxLayout()
        self.layoutPlot.setObjectName(_fromUtf8("layoutPlot"))
        self.verticalLayout.addLayout(self.layoutPlot)
        self.groupBox = QtGui.QGroupBox(self.widgetPlot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.spnMinX = QtGui.QDoubleSpinBox(self.groupBox)
        self.spnMinX.setMinimumSize(QtCore.QSize(0, 0))
        self.spnMinX.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spnMinX.setMaximum(999999999.99)
        self.spnMinX.setObjectName(_fromUtf8("spnMinX"))
        self.gridLayout_3.addWidget(self.spnMinX, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 5, 1, 1)
        self.chkShowGrid = QtGui.QCheckBox(self.groupBox)
        self.chkShowGrid.setObjectName(_fromUtf8("chkShowGrid"))
        self.gridLayout_3.addWidget(self.chkShowGrid, 0, 6, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.spnMaxX = QtGui.QDoubleSpinBox(self.groupBox)
        self.spnMaxX.setMinimumSize(QtCore.QSize(0, 0))
        self.spnMaxX.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spnMaxX.setMaximum(999999999.99)
        self.spnMaxX.setObjectName(_fromUtf8("spnMaxX"))
        self.gridLayout_3.addWidget(self.spnMaxX, 1, 1, 1, 1)
        self.chkAsPlot = QtGui.QCheckBox(self.groupBox)
        self.chkAsPlot.setObjectName(_fromUtf8("chkAsPlot"))
        self.gridLayout_3.addWidget(self.chkAsPlot, 1, 6, 1, 1)
        self.btnRefresh = QtGui.QPushButton(self.groupBox)
        self.btnRefresh.setObjectName(_fromUtf8("btnRefresh"))
        self.gridLayout_3.addWidget(self.btnRefresh, 0, 2, 2, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2.addWidget(self.widgetPlot)

        self.retranslateUi(KmeansDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), KmeansDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), KmeansDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(KmeansDialog)

    def retranslateUi(self, KmeansDialog):
        KmeansDialog.setWindowTitle(_translate("KmeansDialog", "K-means Clustering", None))
        self.label_6.setText(_translate("KmeansDialog", "距离度量：", None))
        item = self.lstStatistics.horizontalHeaderItem(0)
        item.setText(_translate("KmeansDialog", "聚类中心", None))
        item = self.lstStatistics.horizontalHeaderItem(1)
        item.setText(_translate("KmeansDialog", "X坐标", None))
        item = self.lstStatistics.horizontalHeaderItem(2)
        item.setText(_translate("KmeansDialog", "Y坐标", None))
        self.label_3.setText(_translate("KmeansDialog", "聚类中心:", None))
        self.label.setText(_translate("KmeansDialog", "输入图层：", None))
        self.label_7.setText(_translate("KmeansDialog", "聚类数量：", None))
        self.cmbDis.setItemText(0, _translate("KmeansDialog", "欧式距离", None))
        self.cmbDis.setItemText(1, _translate("KmeansDialog", "曼哈顿距离", None))
        self.cmbDis.setItemText(2, _translate("KmeansDialog", "汉明距离", None))
        self.label_2.setText(_translate("KmeansDialog", "输出聚类地图：", None))
        self.openBtn.setText(_translate("KmeansDialog", "···", None))
        self.label_5.setText(_translate("KmeansDialog", "Xmax", None))
        self.chkShowGrid.setText(_translate("KmeansDialog", "显示格网", None))
        self.label_4.setText(_translate("KmeansDialog", "Xmin", None))
        self.chkAsPlot.setText(_translate("KmeansDialog", "折线图", None))
        self.btnRefresh.setText(_translate("KmeansDialog", "刷新", None))

